"""create link table and it relational link support table (file_link_relations)

Revision ID: 892f19efa3a5
Revises: bbb8a1e8b212
Create Date: 2026-05-03 07:06:44.341901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '892f19efa3a5'
down_revision: Union[str, Sequence[str], None] = 'bbb8a1e8b212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )
    op.create_table('file_link_relations',
        sa.Column('file_id', sa.Uuid(), nullable=False),
        sa.Column('link_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
        sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
        sa.PrimaryKeyConstraint('file_id', 'link_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_link_relations')
    op.drop_table('links')
    # ### end Alembic commands ###
